import {notFound} from 'next/navigation';
import type {Metadata} from 'next';
import Link from 'next/link';
import {SiteHeader} from '../../../components/SiteHeader';
import {SiteFooter} from '../../../components/SiteFooter';
import {plansEn} from '../plan-data-en';

export function generateStaticParams(){return Object.keys(plansEn).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const plan=plansEn[slug];if(!plan)return{};return{title:plan.name,description:plan.intro,alternates:{canonical:`/en/plans/${slug}`,languages:{'pt-BR':`/planos/${slug}`,'en-US':`/en/plans/${slug}`}}}}

export default async function Page({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const plan=plansEn[slug];if(!plan)return notFound();return <><SiteHeader/><main id="conteudo" className="planPage">
  <header className="planHero"><div className="shell"><p className="breadcrumbs"><Link href="/en">Home</Link> / <Link href="/en#planos">Plans</Link> / {plan.name}</p>{plan.badge&&<span className="tag staticTag">{plan.badge}</span>}<h1>{plan.name}</h1><h2>{plan.subtitle}</h2><p>{plan.intro}</p><strong>{plan.price}</strong><div className="highlightRow">{plan.highlights.map(x=><span key={x}>{x}</span>)}</div><div className="heroActions"><Link className="button" href="/en/schedule">{plan.cta}</Link><Link className="buttonSecondary" href="/en/schedule">Schedule a conversation</Link></div></div></header>
  <section className="planSection shell"><p className="eyebrow">THIS PLAN FITS IF</p><div className="checkGrid">{plan.fit.map(x=><div key={x}>✓ {x}</div>)}</div></section>
  <section className="planSection soft"><div className="shell"><p className="eyebrow">WHAT BENÊ DOES</p><div className="detailGrid">{plan.sections.map(s=><article key={s.title}><h2>{s.title}</h2><ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></div></section>
  <section className="planSection shell"><p className="eyebrow">WHAT YOU RECEIVE</p><div className="deliverGrid">{plan.receives.map(x=><div key={x}>{x}</div>)}</div><blockquote>Benê does not simply answer questions. We help make your company’s HR work in practice.</blockquote></section>
  <section className="planSection ink"><div className="shell"><p className="eyebrow pale">HOW THE FIRST MONTH WORKS</p><div className="timeline">{[['01','Understand the company','Structure, team, challenges and priorities.'],['02','Organize the foundations','Documents, processes and responsibilities.'],['03','Set priorities','What must happen now and next.'],['04','Join the operation','Benê follows and performs the agreed work.'],['05','Measure and improve','Indicators and continuous evolution.']].map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>
  <section className="planSection shell"><p className="eyebrow">THE BENÊ DIFFERENCE</p><h2>We do not deliver a PDF and disappear.</h2><p className="leadSmall">Benê joins the operation, organizes priorities and brings in the right specialists for each context.</p><blockquote className="handQuote">Benê holds your hand along the way. We stay until you can walk on your own — and, when it still makes sense, even after that.</blockquote><div className="fourCards">{[['ORGANIZE','Processes, documents and routines.'],['EXECUTE','Decisions turned into concrete action.'],['FOLLOW UP','Plans that continue after the meeting.'],['IMPROVE','Data and follow-up for continuous progress.']].map(x=><div key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></div>)}</div></section>
  <section className="planSection careSection"><div className="shell careGrid"><div><p className="eyebrow">CLOSE SUPPORT</p><h2>Clear decisions, guided execution and support when routines become demanding.</h2><p>You always know what is being done, who is involved and what comes next.</p></div><div className="careList">{['Clear ownership','Visible priorities','Follow-up meetings','Manager guidance','Specialists involved when needed','Approval before any extra scope'].map(x=><span key={x}>{x}</span>)}</div></div></section>
  <section className="planSection shell"><p className="eyebrow">TRANSPARENCY</p><h2>Some activities require specific licensed professionals.</h2><p>Legal representation, accounting, payroll not included in the plan, occupational medicine, workplace safety, specialist search, major projects and licenses may be delivered by partners or licensed professionals.</p><p><b>When that happens, we tell you first. No surprises.</b></p><p className="upgrade"><b>When to review the plan:</b> {plan.upgrade}</p></section>
  <section className="cta"><div className="shell"><h2>You do not have to solve HR alone.</h2><p>Tell us how your company works today. We will confirm the right structure before you hire.</p><Link className="button lightButton" href="/en/schedule">Schedule a conversation</Link></div></section>
  </main><SiteFooter/></>}
