export type Article={slug:string;category:string;title:string;description:string;reading:string;intro:string;sections:{title:string;paragraphs:string[];items?:string[]}[];closing:string};

export const articles:Article[]=[
 {slug:'contratacao-sem-improviso',category:'Recrutamento',title:'Contratação sem improviso: um caminho mais seguro para pequenas empresas',description:'Como organizar briefing, critérios, entrevistas e integração para contratar com mais clareza e menos urgência.',reading:'7 min de leitura',intro:'Quando uma vaga aparece, é comum querer publicar o anúncio no mesmo dia. O problema é que a pressa sem critérios transfere a dúvida para todas as etapas seguintes. Contratar melhor começa antes de procurar currículos.',sections:[
  {title:'Comece pelo problema que a vaga precisa resolver',paragraphs:['Antes do cargo, descreva a situação: o que deixou de ser feito, qual resultado está atrasado e como essa pessoa ajudará a operação. Isso evita procurar uma lista genérica de competências que pouco diz sobre o trabalho real.'],items:['Resultado esperado nos primeiros 90 dias','Atividades realmente prioritárias','A quem a pessoa responderá','Quais decisões poderá tomar','O que pode ser ensinado depois da entrada']},
  {title:'Transforme percepção em critérios observáveis',paragraphs:['“Ter perfil”, “ser proativo” ou “vestir a camisa” são expressões abertas demais. Troque rótulos por comportamentos que possam ser verificados durante a seleção.'],items:['Experiência necessária e experiência apenas desejável','Conhecimentos que serão testados ou demonstrados','Situações reais para explorar na entrevista','Critérios iguais para todas as pessoas candidatas']},
  {title:'Conduza entrevistas que ajudam a decidir',paragraphs:['Uma boa entrevista combina perguntas consistentes com espaço para aprofundar exemplos. Peça contexto, ação e resultado. Registre evidências logo após cada conversa para reduzir o peso da memória e da afinidade pessoal.','Quando mais de uma liderança participa, alinhe antes quem avalia cada dimensão. A decisão melhora quando as pessoas comparam evidências, não impressões soltas.']},
  {title:'Não abandone a contratação no aceite',paragraphs:['A chegada confirma — ou desfaz — a promessa feita durante o processo seletivo. Prepare acessos, agenda, responsabilidades e conversas de acompanhamento. Um onboarding simples já reduz dúvidas e acelera a autonomia.'],items:['Primeiro dia com responsável definido','Objetivos da primeira semana','Check-ins de 7, 15 e 30 dias','Critérios claros para o período de experiência']}
 ],closing:'Se a vaga está aberta e a rotina não pode parar, a Benê pode organizar o processo, fazer a triagem e apresentar uma shortlist com critérios claros.'},
 {slug:'quando-a-empresa-precisa-de-rh',category:'Gestão de pessoas',title:'Quando a empresa precisa de RH — antes de virar uma urgência',description:'Sinais práticos de que a gestão de pessoas já precisa de uma rotina, mesmo sem montar um departamento interno.',reading:'6 min de leitura',intro:'Uma empresa não precisa esperar chegar a cinquenta pessoas para cuidar de RH. A necessidade costuma aparecer quando decisões sobre contratação, integração, desempenho e conflitos começam a competir com o tempo de quem lidera o negócio.',sections:[
  {title:'O primeiro sinal é a dependência da memória',paragraphs:['Se admissão, onboarding, feedback e desligamento acontecem de um jeito diferente a cada vez, a empresa já tem um processo — só que informal. O risco não está apenas no documento ausente, mas na dificuldade de repetir uma boa experiência.'],items:['Informações espalhadas entre mensagens e planilhas','Responsabilidades que ninguém consegue explicar','Novas pessoas dependentes de uma única liderança','Problemas recorrentes sem histórico de decisão']},
  {title:'O segundo sinal é a liderança sobrecarregada',paragraphs:['Quando todo conflito, dúvida ou contratação sobe para o dono, o crescimento encontra um teto. RH não significa retirar a liderança da decisão. Significa organizar dados, preparar conversas e criar critérios para que ela decida melhor.']},
  {title:'O terceiro sinal aparece nos resultados',paragraphs:['Vagas que demoram, saídas inesperadas, erros no período de experiência e falta de clareza sobre desempenho têm custo operacional. Mesmo sem um indicador sofisticado, a repetição desses eventos mostra que é hora de estruturar a rotina.']},
  {title:'Comece do tamanho da empresa',paragraphs:['Nem toda pequena empresa precisa contratar uma pessoa interna de RH. É possível começar com um diagnóstico, organizar os processos essenciais ou contar com apoio contínuo sob demanda. O desenho certo depende do porte, do volume e da complexidade — não de uma fórmula pronta.'],items:['Mapear o que mais toma tempo hoje','Escolher de uma a três prioridades','Definir quem decide e quem executa','Criar uma cadência simples de acompanhamento']}
 ],closing:'O Diagnóstico Benê ajuda a identificar a dor prioritária e a rota mais adequada sem obrigar você a conhecer o nome da solução.'},
 {slug:'dono-centraliza-decisoes',category:'Liderança',title:'Quando o dono centraliza tudo: como criar autonomia sem perder o controle',description:'Um caminho prático para tirar decisões operacionais do colo do dono e fortalecer gestores.',reading:'7 min de leitura',intro:'Centralizar costuma começar como cuidado: a pessoa fundadora conhece o cliente, protege o padrão e resolve rápido. Com o crescimento, o mesmo comportamento passa a atrasar decisões, confundir prioridades e impedir que lideranças amadureçam.',sections:[
  {title:'Identifique o que está realmente centralizado',paragraphs:['Nem toda decisão deve ser delegada. Comece registrando, durante uma semana, quais assuntos chegam à liderança e por quê. A lista costuma revelar três causas: papéis pouco claros, critérios inexistentes ou receio de errar.']},
  {title:'Delegue contexto, não apenas tarefas',paragraphs:['Dizer “resolva isso” sem explicar limites cria insegurança. Uma delegação útil esclarece o resultado esperado, os recursos disponíveis, o que pode ser decidido sozinho e em que situação a liderança deve ser chamada.'],items:['Qual resultado precisa ser alcançado','Quais limites não podem ser ultrapassados','Quando comunicar e quando pedir autorização','Como registrar a decisão e o aprendizado']},
  {title:'Crie rituais curtos de acompanhamento',paragraphs:['Autonomia não é ausência. Reuniões breves e previsíveis permitem corrigir rota sem retomar cada tarefa. O gestor leva dados, decisões e impedimentos; o dono oferece contexto e remove barreiras.']},
  {title:'Use o erro como informação de processo',paragraphs:['Se a mesma falha se repete, procure o ponto ausente: critério, treinamento, ferramenta ou responsabilidade. Corrigir apenas a pessoa mantém o problema vivo. O objetivo é transformar decisões boas em uma forma de trabalhar que possa ser repetida.']},
  {title:'O RH ajuda a sustentar a mudança',paragraphs:['Papéis, competências, feedbacks e indicadores dão suporte à delegação. Um RH próximo ajuda a organizar essas bases, preparar gestores e acompanhar a evolução sem tirar da liderança o papel de conduzir o negócio.']}
 ],closing:'A Benê coordena esse caminho com processos úteis, orientação aos gestores e acompanhamento compatível com o momento da empresa.'}
];

export function getArticle(slug:string){return articles.find(article=>article.slug===slug)}
