'use client';
/* eslint-disable @next/next/no-img-element */
import {useEffect,useMemo,useRef,useState} from 'react';
import {SiteHeader} from './components/SiteHeader';
import {SiteFooter} from './components/SiteFooter';
import {NewsletterSection} from './components/NewsletterForm';
import {BrandMarquee} from './components/BrandMarquee';
import {whatsappUrl} from './lib/site';
type Pain='vaga'|'estrutura'|'recorrente'|'sensivel';
type A={label:string;value:number;pain?:Pain}; type Q={id:string;title:string;answers:A[]};
const questions:Q[]=[
{id:'porte',title:'Quantas pessoas trabalham na empresa?',answers:[{label:'1 a 7',value:2},{label:'8 a 20',value:8},{label:'21 a 60',value:10},{label:'Mais de 60',value:4}]},
{id:'estrutura',title:'Quem cuida dos temas de pessoas hoje?',answers:[{label:'RH com processos claros',value:1},{label:'Uma pessoa acumula a função',value:6,pain:'estrutura'},{label:'Sócios e líderes',value:8,pain:'estrutura'},{label:'Ninguém de forma definida',value:10,pain:'estrutura'}]},
{id:'dp',title:'Folha e departamento pessoal estão organizados?',answers:[{label:'Sim, com parceiro ou equipe',value:1},{label:'Em parte',value:4},{label:'Não; esta é a única necessidade',value:0}]},
{id:'contratacao',title:'Como estão as contratações?',answers:[{label:'Sem vagas no momento',value:0},{label:'Planejadas para os próximos meses',value:4,pain:'recorrente'},{label:'Uma vaga aberta ou urgente',value:10,pain:'vaga'},{label:'Contratações recorrentes',value:8,pain:'recorrente'}]},
{id:'turnover',title:'Rotatividade ou risco de saída afetam o negócio?',answers:[{label:'Não de forma relevante',value:0},{label:'Há sinais, mas sem medição',value:4,pain:'estrutura'},{label:'Sim, com impacto claro',value:8,pain:'recorrente'}]},
{id:'onboarding',title:'Novas pessoas têm onboarding definido?',answers:[{label:'Sim, documentado',value:0},{label:'Parcialmente',value:3,pain:'estrutura'},{label:'Não',value:6,pain:'estrutura'}]},
{id:'gestao',title:'Papéis, desempenho e feedbacks estão claros?',answers:[{label:'Sim',value:0},{label:'Em parte',value:4,pain:'estrutura'},{label:'Não',value:7,pain:'recorrente'}]},
{id:'desenvolvimento',title:'Cargos, salários e treinamento acompanham o crescimento?',answers:[{label:'Sim',value:0},{label:'Precisam de revisão pontual',value:3,pain:'estrutura'},{label:'Precisam de acompanhamento contínuo',value:6,pain:'recorrente'}]},
{id:'conflitos',title:'Existe denúncia, assédio, conflito grave ou risco jurídico?',answers:[{label:'Não',value:0},{label:'Conflito de gestão, sem denúncia',value:5,pain:'estrutura'},{label:'Sim ou não tenho certeza',value:0,pain:'sensivel'}]},
{id:'urgencia',title:'Em quanto tempo você precisa avançar?',answers:[{label:'Até 15 dias',value:10},{label:'Até 30 dias',value:7},{label:'Em 2 a 3 meses',value:3},{label:'Só pesquisando',value:0}]},
{id:'orcamento',title:'Há orçamento compatível com a rota apresentada?',answers:[{label:'Sim',value:5},{label:'Preciso avaliar a proposta',value:3},{label:'Ainda não há orçamento',value:0}]},
{id:'consentimento',title:'Posso usar estas respostas só para gerar sua leitura local?',answers:[{label:'Sim, gerar minha leitura',value:6},{label:'Não, voltar ao início',value:0}]},
];
const plans=[['Start','R$ 1.500/mês','Até 10 pessoas · 1 vaga padrão ativa','R&S, onboarding e suporte mensal'],['Pro','R$ 3.500/mês','Até 30 pessoas · 2 vagas padrão ativas','Start + gestão, treinamento e cultura'],['Full','R$ 7.000/mês','Até 60 pessoas · 3 vagas padrão ativas','Pro + RH estratégico, educação corporativa e apoio de compliance']];
function track(event:string,props:Record<string,string|number|boolean>={}){if(typeof window==='undefined')return;const row={event,timestamp:new Date().toISOString(),...props};const old=JSON.parse(localStorage.getItem('bene_events')||'[]');localStorage.setItem('bene_events',JSON.stringify([...old,row].slice(-100)))}
export default function Home(){
 const[step,setStep]=useState(0),[answers,setAnswers]=useState<A[]>([]),[done,setDone]=useState(false);
 const questionRef=useRef<HTMLHeadingElement>(null);
 const didInteract=useRef(false);
 useEffect(()=>{const u=new URLSearchParams(location.search);['utm_source','utm_medium','utm_campaign','utm_content','utm_term'].forEach(k=>{const v=u.get(k);if(v)sessionStorage.setItem(k,v)});track('page_view',{source:u.get('utm_source')||'direct'})},[]);
 useEffect(()=>{if(didInteract.current)questionRef.current?.focus();else didInteract.current=true},[step,done]);
 const sensitive=answers.some(a=>a.pain==='sensivel');
 const pain=useMemo(()=>{const c:Record<string,number>={};answers.forEach(a=>{if(a.pain)c[a.pain]=(c[a.pain]||0)+1});return Object.entries(c).sort((a,b)=>b[1]-a[1])[0]?.[0]||'estrutura'},[answers]);
 const result=sensitive?['Atendimento humano necessário','Conversa reservada','O tema exige análise humana e não seguirá por automação. A Benê fará uma triagem cuidadosa e, quando necessário, orientará a busca de profissional habilitado.']:pain==='vaga'?['Necessidade de contratação','R&S sob demanda','A rota indicada é conduzir uma vaga padrão com briefing, triagem, entrevistas iniciais e shortlist.']:pain==='recorrente'?['Demanda contínua','RH por assinatura','A necessidade pede continuidade. O plano depende do porte e do volume real de demandas.']:['RH pede estrutura','Diagnóstico + Estruturação','A rota indicada é organizar gargalos, até três processos e um plano de 90 dias.'];
 function reset(){setStep(0);setAnswers([]);setDone(false)}
 function choose(a:A){if(questions[step].id==='consentimento'&&a.label.startsWith('Não'))return reset();const n=[...answers,a];setAnswers(n);track('diagnostic_answer',{question:questions[step].id,step:step+1});if(a.pain==='sensivel'){setDone(true);track('diagnostic_sensitive_stop',{step:step+1});return}if(step===questions.length-1){setDone(true);track('diagnostic_complete',{score:n.reduce((s,x)=>s+x.value,0),sensitive:false})}else setStep(step+1)}
 const cta=(label:string)=><a className="button" href="#diagnostico" onClick={()=>track('cta_click',{label})}>{label}</a>;
 return <><SiteHeader/><main id="conteudo">
 <section className="hero" id="top"><div className="shell heroGrid"><div><p className="eyebrow">RH SOB DEMANDA PARA PMES</p><h1>Gestão de pessoas sob medida, <em>sem ampliar sua equipe interna.</em></h1><p className="lead">Contratação, organização e gestão de pessoas para sua empresa crescer com mais clareza - enquanto você cuida do negócio.</p><div className="actions">{cta('Quero meu Diagnóstico Benê')}<a className="textLink" href="#recrutamento">Preciso contratar →</a></div><p className="micro">Diagnóstico gratuito · resultado na hora · conversa de até 30 minutos com a Benê, se você quiser avançar</p></div><aside className="heroCard"><span>GENTE BOA CUIDANDO DE GENTE. ✦</span><blockquote>Seu RH funcionando, você focado no negócio.</blockquote><p>Uma rota objetiva para cada momento: contratar, estruturar ou ter apoio contínuo.</p></aside></div></section>
 <section className="section shell" id="solucoes"><p className="eyebrow">COMECE PELA DOR</p><div className="sectionTitle situationTitle"><h2>O que está pesando na sua rotina hoje?</h2><p>Você não precisa saber o nome da solução. A Benê ajuda a encontrar o próximo passo.</p></div><div className="painGrid">{[['Preciso contratar','R&S sob demanda','#recrutamento'],['Meu RH virou bagunça','Diagnóstico + Estruturação','#estruturacao'],['Preciso de RH contínuo','Planos mensais','#planos'],['Não sei por onde começar','Diagnóstico gratuito','#diagnostico']].map((x,i)=><a className="pain" href={x[2]} key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p><b>Ver caminho →</b></a>)}</div></section>
 <section className="section warm" id="recrutamento"><div className="shell offerGrid"><div><p className="eyebrow">ROTA 01 · NECESSIDADE PONTUAL</p><h2>A pessoa certa para a vaga, sem parar sua operação.</h2><p className="bodyText">Briefing, divulgação, triagem, entrevistas iniciais e shortlist de até três pessoas para vagas administrativas, comerciais ou operacionais.</p><ul><li>Shortlist em até 15 dias úteis após briefing aprovado</li><li>50% na contratação e 50% na shortlist</li><li>Uma reposição sem nova taxa em até 30 dias após a admissão, se cargo, remuneração e perfil forem mantidos</li></ul></div><div className="priceCard"><p>R&S sob demanda</p><strong>R$ 1.500</strong><span>por vaga padrão</span><small>Busca executiva, perfil técnico raro, volume, testes pagos, admissional e folha não inclusos.</small>{cta('Quero avaliar minha vaga')}</div></div></section>
 <section className="section shell" id="estruturacao"><div className="offerGrid reverse"><div className="priceCard dark"><p>Diagnóstico + Estruturação</p><strong>R$ 2.500</strong><span>projeto fechado</span><small>Indicado para empresas com até 20 pessoas e uma única unidade. Entrega em até 10 dias úteis.</small>{cta('Quero organizar meu RH')}</div><div><p className="eyebrow">ROTA 02 · ORGANIZAÇÃO</p><h2>Clareza para parar de apagar incêndios.</h2><p className="bodyText">Mapa de gargalos, prioridades, até três processos, plano de 90 dias e reunião de entrega, com uma rodada de ajustes.</p><ul><li>100% na contratação ou 2 parcelas no cartão</li><li>Sem implantação contínua, R&S, folha ou parecer jurídico</li><li>Escopo validado antes da execução</li></ul></div></div></section>
 <section className="section ink" id="planos"><div className="shell"><p className="eyebrow pale">ROTA 03 · APOIO CONTÍNUO</p><div className="sectionTitle light"><h2>RH por assinatura, na medida do crescimento.</h2><p>A Benê coordena uma rede de especialistas e parceiros para atender cada fase do seu RH com o conhecimento certo.</p></div><div className="plans">{plans.map((p,i)=><article className={i===1?'plan featured':'plan'} key={p[0]}>{i===1&&<span className="tag">MAIS INDICADO</span>}<h3>Benê {p[0]}</h3><strong>{p[1]}</strong><p>{p[2]}</p><hr/><p>{p[3]}</p><a href={`/planos/${p[0].toLowerCase()}`}>Ver se é para mim →</a></article>)}</div><p className="terms">Vigência mínima de três meses. Demandas fora do escopo são avaliadas e aprovadas antes da execução.</p></div></section>
 <section className="section shell comparison" aria-labelledby="plan-comparison-title"><p className="eyebrow">COMPARE OS PLANOS</p><h2 id="plan-comparison-title">Uma estrutura que cresce com a empresa.</h2><p className="tableHint" id="plan-comparison-hint">Em telas pequenas, deslize horizontalmente para comparar todos os planos.</p><div className="compareTable" role="region" aria-label="Comparação dos planos Benê RH" aria-describedby="plan-comparison-hint" tabIndex={0}><table><thead><tr><th scope="col">O que está incluído</th><th scope="col">Start</th><th scope="col">Pro</th><th scope="col">Full</th></tr></thead><tbody>{[['Colaboradores','10','30','60'],['Vagas simultâneas','1','2','3'],['Rotina de RH','✓','✓','✓'],['Onboarding','✓','✓','✓'],['Suporte ao gestor','✓','✓','✓'],['Gestão de pessoas','-','✓','✓'],['Treinamento e cultura','-','✓','✓'],['Indicadores avançados','-','-','✓'],['RH estratégico','-','-','✓'],['Performance estruturada','-','-','✓'],['Educação corporativa','-','-','✓'],['Dashboard executivo','-','-','✓']].map(r=><tr key={r[0]}><th scope="row">{r[0]}</th>{r.slice(1).map((c,i)=><td key={i}>{c==='✓'?<><span aria-hidden="true">✓</span><span className="visuallyHidden">Incluído</span></>:c==='-'?<><span aria-hidden="true">—</span><span className="visuallyHidden">Não incluído</span></>:c}</td>)}</tr>)}</tbody></table></div></section>
 <section className="section shell" id="como"><p className="eyebrow">SIMPLES DESDE O PRIMEIRO CONTATO</p><div className="steps">{[['01','Diagnóstico','Maturidade, dor prioritária e rota.'],['02','Conversa','Até 30 minutos para validar o contexto.'],['03','Proposta','Escopo, prazo e limites claros.'],['04','Execução','Status, evidências e próximos passos.']].map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
 <section className="section diagnostic" id="diagnostico"><div className="shell diagnosticGrid"><div><p className="eyebrow">DIAGNÓSTICO BENÊ</p><h2>Descubra a prioridade do seu RH.</h2><p>São 12 perguntas. A leitura é gerada no seu navegador; suas respostas não são enviadas à Benê.</p><div className="privacyNote">Não descreva nomes, denúncias ou informações pessoais. Se houver situação sensível, o diagnóstico para imediatamente e orienta um contato reservado.</div></div><div className="quiz">{!done?<><div className="progress" role="progressbar" aria-label="Progresso do diagnóstico" aria-valuemin={1} aria-valuemax={questions.length} aria-valuenow={step+1}><span style={{width:`${((step+1)/questions.length)*100}%`}}/></div><small>PERGUNTA {step+1} DE {questions.length}</small><h3 ref={questionRef} tabIndex={-1}>{questions[step].title}</h3><div className="options">{questions[step].answers.map(a=><button key={a.label} onClick={()=>choose(a)}>{a.label}<span aria-hidden="true">→</span></button>)}</div>{step>0&&<button className="reset" onClick={()=>{setAnswers(answers.slice(0,-1));setStep(step-1)}}>Voltar</button>}</>:<><small>LEITURA INICIAL</small><h3 ref={questionRef} tabIndex={-1}>{result[0]}</h3><p>{result[2]}</p><div className="route"><span>ROTA INDICADA</span><strong>{result[1]}</strong></div>{sensitive&&<div className="privacyNote"><b>Importante:</b> não envie nomes, relatos, documentos ou provas pelo primeiro contato. Peça apenas uma conversa reservada.</div>}<div className="resultActions"><a className="button" href={whatsappUrl(sensitive?'Olá, preciso solicitar uma conversa reservada sobre uma situação sensível de pessoas. Não enviarei detalhes por aqui.':'Olá, concluí o Diagnóstico Benê e a rota indicada foi: '+result[1]+'. Quero entender o próximo passo.')} target="_blank" rel="noopener noreferrer">Conversar pelo WhatsApp</a><a className="buttonSecondary" href="/agendar">Agendar conversa</a><button className="reset" onClick={reset}>Refazer</button></div><p className="micro">A leitura é inicial e não substitui análise humana, parecer jurídico ou proposta comercial.</p></>}</div></div></section>
 <section className="section shell"><div className="about"><figure className="portrait"><img src="/amanda-stamboni.webp" width="760" height="950" loading="lazy" decoding="async" alt="Amanda Stamboni, fundadora da Benê RH"/><figcaption>Amanda Stamboni</figcaption></figure><div><p className="eyebrow">A LIDERANÇA POR TRÁS DA BENÊ</p><h2>Uma rede de especialistas, coordenada de perto.</h2><p className="bodyText">Amanda Stamboni está à frente da estratégia, do relacionamento com cada empresa e das decisões que exigem olhar humano. Conforme a necessidade, ela articula especialistas e parceiros de confiança para reunir o conhecimento certo em recrutamento, gestão de pessoas, desenvolvimento e áreas complementares.</p><p className="credentials">Administradora com CRA ativo · Técnica em RH · Cientista de Dados · Fundadora da Consultoria Stamboni · Cofundadora da Zênite Escola de Negócios</p></div></div></section>
 <section className="section blogPreview"><div className="shell"><p className="eyebrow">CONTEÚDO PARA QUEM LIDERA</p><div className="sectionTitle"><h2>RH explicado sem complicação.</h2><p>Leituras práticas para contratar melhor, organizar a casa e saber quando pedir apoio.</p></div><div className="previewGrid"><a href="/blog/contratacao-sem-improviso"><span>RECRUTAMENTO</span><h3>Contratação sem improviso</h3><p>Um roteiro prático para tirar a vaga da urgência e melhorar a decisão.</p><b>Ler artigo →</b></a><a href="/blog/quando-a-empresa-precisa-de-rh"><span>GESTÃO DE PESSOAS</span><h3>Quando a empresa precisa de RH?</h3><p>Os sinais de que a rotina de pessoas já não cabe apenas no colo do dono.</p><b>Ler artigo →</b></a><a href="/blog/dono-centraliza-decisoes"><span>LIDERANÇA</span><h3>Quando o dono centraliza tudo</h3><p>Como criar clareza e autonomia sem perder o controle do negócio.</p><b>Ler artigo →</b></a></div><a className="textLink blogAll" href="/blog">Ver todos os artigos →</a></div></section>
 <section className="section faq shell" id="faq"><p className="eyebrow">DÚVIDAS FREQUENTES</p><h2>Antes de conversar, vale saber.</h2>{[['A Benê substitui meu departamento pessoal?','Não. Folha e obrigações trabalhistas permanecem com profissionais habilitados.'],['Preciso contratar um plano mensal?','Não. Você pode começar por uma vaga padrão ou por estruturação.'],['O Diagnóstico entrega um plano completo?','Não. Ele indica maturidade, dor prioritária e rota.'],['Posso cancelar a assinatura a qualquer momento?','Há vigência mínima de três meses e depois aviso de 30 dias.'],['A Benê trata denúncias ou temas jurídicos?','Situações sensíveis exigem atendimento humano e podem ser encaminhadas a profissional habilitado.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section>
 <section className="cta"><div className="shell"><p className="eyebrow">SEU PRÓXIMO PASSO PODE SER SIMPLES ✦</p><h2>Comece entendendo o que seu RH precisa agora.</h2><div className="centerActions">{cta('Fazer o Diagnóstico Benê')}<a className="button lightButton" href="/agendar">Agendar uma conversa</a></div></div></section>
 <NewsletterSection/>
 <BrandMarquee/>
 </main><SiteFooter/></>
}



