import type {Metadata} from 'next';
/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import {SiteHeader} from '../components/SiteHeader';
import {SiteFooter} from '../components/SiteFooter';
import {NewsletterSection} from '../components/NewsletterForm';
import {BrandMarquee} from '../components/BrandMarquee';

export const metadata:Metadata={title:'On-demand HR for growing companies',description:'Hiring, people operations and HR management for small and medium-sized businesses.',alternates:{languages:{'pt-BR':'/','en-US':'/en'}}};

const plans=[['Start','R$ 1,500/month','Up to 10 people · 1 standard active role','Recruiting, onboarding and monthly support'],['Pro','R$ 3,500/month','Up to 30 people · 2 standard active roles','Start + management, training and culture'],['Full','R$ 7,000/month','Up to 60 people · 3 standard active roles','Pro + strategic HR, corporate education and compliance support']];

export default function Page(){return <><SiteHeader/><main id="conteudo">
  <section className="hero"><div className="shell heroGrid"><div><p className="eyebrow">ON-DEMAND HR FOR GROWING BUSINESSES</p><h1>People management built for your reality, <em>without expanding your internal team.</em></h1><p className="lead">Hiring, organization and people management so your company can grow with clarity while you focus on the business.</p><div className="actions"><a className="button" href="#diagnostico">Start the Benê Diagnosis</a><a className="textLink" href="#recrutamento">I need to hire →</a></div><p className="micro">Free diagnosis · instant result · optional conversation of up to 30 minutes</p></div><aside className="heroCard"><span>GOOD PEOPLE TAKING CARE OF PEOPLE. ✦</span><blockquote>Your HR working. You focused on the business.</blockquote><p>A clear route for every stage: hire, structure or receive ongoing support.</p></aside></div></section>
  <section className="section shell" id="solucoes"><p className="eyebrow">START WITH THE CHALLENGE</p><div className="sectionTitle situationTitle"><h2>What is weighing on your routine today?</h2><p>You do not need to know the name of the solution. Benê helps you identify the next step.</p></div><div className="painGrid">{[['I need to hire','On-demand recruiting','#recrutamento'],['Our HR is disorganized','Diagnosis + Structuring','#estruturacao'],['I need ongoing HR','Monthly plans','#planos'],['I do not know where to start','Free diagnosis','#diagnostico']].map((x,i)=><a className="pain" href={x[2]} key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p><b>See route →</b></a>)}</div></section>
  <section className="section warm" id="recrutamento"><div className="shell offerGrid"><div><p className="eyebrow">ROUTE 01 · ONE-TIME NEED</p><h2>The right person for the role, without stopping your operation.</h2><p className="bodyText">Role briefing, promotion, screening, initial interviews and a shortlist of up to three people for administrative, commercial or operational roles.</p><ul><li>Shortlist within 15 business days after brief approval</li><li>50% upon hiring and 50% upon shortlist delivery</li><li>One replacement at no fee within 30 days after hiring, if role, compensation and profile remain unchanged</li></ul></div><div className="priceCard"><p>On-demand recruiting</p><strong>R$ 1,500</strong><span>per standard role</span><small>Executive search, rare technical profiles, volume hiring, paid tests, occupational exams and payroll are not included.</small><a className="button" href="#diagnostico">Assess my role</a></div></div></section>
  <section className="section shell" id="estruturacao"><div className="offerGrid reverse"><div className="priceCard dark"><p>Diagnosis + Structuring</p><strong>R$ 2,500</strong><span>fixed-scope project</span><small>Recommended for companies with up to 20 people and one location. Delivery within 10 business days.</small><a className="button" href="#diagnostico">Organize my HR</a></div><div><p className="eyebrow">ROUTE 02 · ORGANIZATION</p><h2>Clarity to stop putting out fires.</h2><p className="bodyText">A map of bottlenecks and priorities, up to three processes, a 90-day plan and a delivery meeting with one adjustment round.</p><ul><li>Full payment at hiring or two card installments</li><li>Ongoing implementation, recruiting, payroll and legal opinions are not included</li><li>Scope approved before execution</li></ul></div></div></section>
  <section className="section ink" id="planos"><div className="shell"><p className="eyebrow pale">ROUTE 03 · ONGOING SUPPORT</p><div className="sectionTitle light"><h2>HR subscription support that grows with the business.</h2><p>Benê coordinates specialists and partners so each stage receives the right expertise.</p></div><div className="plans">{plans.map((p,i)=><article className={i===1?'plan featured':'plan'} key={p[0]}>{i===1&&<span className="tag">MOST POPULAR</span>}<h3>Benê {p[0]}</h3><strong>{p[1]}</strong><p>{p[2]}</p><hr/><p>{p[3]}</p><Link href={`/en/plans/${p[0].toLowerCase()}`}>See if it fits →</Link></article>)}</div><p className="terms">Three-month minimum term. Out-of-scope requests are assessed and approved before execution.</p></div></section>
  <section className="section shell" id="como"><p className="eyebrow">SIMPLE FROM THE FIRST CONTACT</p><div className="steps">{[['01','Diagnosis','Maturity, priority challenge and route.'],['02','Conversation','Up to 30 minutes to validate the context.'],['03','Proposal','Clear scope, timeline and limits.'],['04','Execution','Status, evidence and next steps.']].map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
  <section className="section diagnostic" id="diagnostico"><div className="shell diagnosticGrid"><div><p className="eyebrow">BENÊ DIAGNOSIS</p><h2>Identify your current HR priority.</h2><p>The initial reading happens in your browser. Do not include names, complaints, health information or documents.</p><div className="privacyNote">If the situation involves harassment, a complaint, health or legal risk, request a confidential human conversation without sharing details in the first contact.</div></div><div className="quiz"><small>CHOOSE THE CLOSEST SITUATION</small><h3>What does your company need most right now?</h3><div className="options"><a href="#recrutamento">An open or urgent role <span>→</span></a><a href="#estruturacao">Organize people processes <span>→</span></a><a href="#planos">Ongoing HR support <span>→</span></a><Link href="/en/schedule">A confidential human conversation <span>→</span></Link></div><p className="micro">This is an initial guide and does not replace professional, legal or organizational analysis.</p></div></div></section>
  <section className="section shell"><div className="about"><figure className="portrait"><img src="/amanda-stamboni.webp" width="760" height="950" loading="lazy" alt="Amanda Stamboni, founder of Benê RH"/><figcaption>Amanda Stamboni</figcaption></figure><div><p className="eyebrow">THE LEADERSHIP BEHIND BENÊ</p><h2>A network of specialists, closely coordinated.</h2><p className="bodyText">Amanda Stamboni leads strategy, client relationships and decisions that require human judgment. Depending on the need, she brings together trusted specialists and partners in recruiting, people management, development and complementary fields.</p><p className="credentials">Business administrator with active CRA registration · HR technician · Data scientist · Founder of Consultoria Stamboni · Co-founder of Zênite Escola de Negócios</p></div></div></section>
  <section className="section blogPreview"><div className="shell"><p className="eyebrow">CONTENT FOR LEADERS</p><div className="sectionTitle"><h2>HR explained without complications.</h2><p>Practical reading to hire better, organize the business and know when to ask for support.</p></div><div className="previewGrid"><Link href="/en/blog/hiring-without-improvisation"><span>RECRUITING</span><h3>Hiring without improvisation</h3><p>A practical route to move a role out of urgency and improve the decision.</p><b>Read article →</b></Link><Link href="/en/blog/when-a-company-needs-hr"><span>PEOPLE MANAGEMENT</span><h3>When does a company need HR?</h3><p>Signs that people operations can no longer sit only with the owner.</p><b>Read article →</b></Link><Link href="/en/blog/when-the-owner-centralizes-decisions"><span>LEADERSHIP</span><h3>When the owner centralizes everything</h3><p>How to build clarity and autonomy without losing control.</p><b>Read article →</b></Link></div></div></section>
  <section className="section faq shell" id="faq"><p className="eyebrow">FREQUENT QUESTIONS</p><h2>Useful answers before we talk.</h2>{[['Does Benê replace payroll administration?','No. Payroll and statutory obligations remain with licensed professionals.'],['Do I need a monthly plan?','No. You can begin with one standard role or a structuring project.'],['Does the diagnosis deliver a complete plan?','No. It indicates maturity, the priority challenge and a suitable route.'],['Can I cancel at any time?','There is a three-month minimum term followed by 30 days notice.'],['Does Benê handle complaints or legal matters?','Sensitive matters require human support and may be referred to a licensed professional.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section>
  <NewsletterSection locale="en"/>
  <BrandMarquee locale="en"/>
  <section className="cta"><div className="shell"><p className="eyebrow">YOUR NEXT STEP CAN BE SIMPLE ✦</p><h2>Start by understanding what your HR needs now.</h2><div className="centerActions"><a className="button" href="#diagnostico">Start the Benê Diagnosis</a><Link className="button lightButton" href="/en/schedule">Schedule a conversation</Link></div></div></section>
</main><SiteFooter/></>}

