import type {Plan} from './plan-data';
import Link from 'next/link';
import {SiteHeader} from '../components/SiteHeader';
import {SiteFooter} from '../components/SiteFooter';
import {StructuredData} from '../components/StructuredData';
import {SITE_URL,whatsappUrl} from '../lib/site';
const firstMonth=[['01','Entendemos sua empresa','Estrutura, equipe, dores, processos e prioridades.'],['02','Organizamos a casa','Documentos, processos, responsabilidades e rotina.'],['03','Definimos prioridades','O que precisa ser resolvido agora e ao longo dos próximos meses.'],['04','Entramos na operação','A Benê acompanha e executa as atividades previstas no plano.'],['05','Medimos e melhoramos','Indicadores, acompanhamento e evolução contínua.']];
export default function PlanDetail({plan}:{plan:Plan}){
 const contact=whatsappUrl(`Olá, conheci o ${plan.name} no site da Benê RH e quero confirmar se ele faz sentido para minha empresa.`);
 const schema={'@context':'https://schema.org','@type':'Service',name:plan.name,description:plan.intro,url:`${SITE_URL}/planos/${plan.slug}`,provider:{'@type':'Organization',name:'Benê RH'},offers:{'@type':'Offer',price:plan.price.match(/[\d.]+/)?.[0].replace(/\./g,'')||'',priceCurrency:'BRL',description:'Valor mensal para escopo padrão. Vigência mínima de três meses; contratação formalizada por proposta e contrato.'}};
 return <><StructuredData data={schema}/><SiteHeader/><main className="planPage" id="conteudo">
 <header className="planHero"><div className="shell"><p className="breadcrumbs"><Link href="/">Início</Link> / <Link href="/#planos">Planos</Link> / {plan.name}</p>{plan.badge&&<span className="tag staticTag">{plan.badge}</span>}<h1>{plan.name}</h1><h2>{plan.subtitle}</h2><p>{plan.intro}</p><strong>{plan.price}</strong><div className="highlightRow">{plan.highlights.map(x=><span key={x}>{x}</span>)}</div><div className="heroActions"><a className="button" href={contact} target="_blank" rel="noopener noreferrer">{plan.cta}</a><Link className="buttonSecondary" href="/agendar">Agendar conversa</Link></div></div></header>
 <section className="planSection shell"><p className="eyebrow">ESTE PLANO É PARA VOCÊ SE</p><div className="checkGrid">{plan.fit.map(x=><div key={x}>✓ {x}</div>)}</div></section>
 <section className="planSection soft"><div className="shell"><p className="eyebrow">O QUE A BENÊ FAZ</p><div className="detailGrid">{plan.sections.map(s=><article key={s.title}><h2>{s.title}</h2><ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul>{s.title==='Recrutamento e seleção'&&<details><summary>O que é uma vaga padrão?</summary><p>Posições operacionais, administrativas ou comerciais de complexidade compatível com o plano. Vagas executivas, altamente técnicas, de grande volume ou com hunting especializado recebem avaliação específica.</p></details>}</article>)}</div></div></section>
 <section className="planSection shell"><p className="eyebrow">O QUE VOCÊ RECEBE</p><div className="deliverGrid">{plan.receives.map(x=><div key={x}>{x}</div>)}</div><blockquote>A Benê não entra apenas para responder dúvidas. A gente ajuda a colocar o RH da empresa para funcionar.</blockquote></section>
 <section className="planSection ink"><div className="shell"><p className="eyebrow pale">COMO FUNCIONA O PRIMEIRO MÊS</p><div className="timeline">{firstMonth.map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>
 <section className="planSection shell"><p className="eyebrow">DIFERENCIAL BENÊ</p><h2>Não somos a consultoria que entrega um PDF e vai embora.</h2><p className="leadSmall">A Benê entra na operação. Organiza, estrutura, acompanha, orienta e ajuda a executar o RH da empresa.</p><blockquote className="handQuote">A Benê segura sua mão durante o caminho. Não soltamos até que você caminhe sozinho. E, se ainda fizer sentido, nem depois disso.</blockquote><div className="fourCards">{[['ORGANIZAR','Processos, documentos, responsabilidades e rotinas.'],['EXECUTAR','Decisões transformadas em atividades concretas.'],['ACOMPANHAR','Planos que não morrem depois da reunião.'],['MELHORAR','Dados e acompanhamento para evoluir continuamente.']].map(x=><div key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></div>)}</div></section>
 <section className="planSection careSection"><div className="shell careGrid"><div><p className="eyebrow">ACOMPANHAMENTO PRÓXIMO</p><h2>Decisão clara, execução acompanhada e apoio quando a rotina apertar.</h2><p>A Benê coordena o trabalho, organiza prioridades e reúne os especialistas adequados ao contexto da empresa. Você sempre sabe o que está sendo feito, quem participa e qual é o próximo passo.</p></div><div className="careList"><span>Responsável definido</span><span>Prioridades visíveis</span><span>Reuniões de acompanhamento</span><span>Orientação para gestores</span><span>Especialistas acionados conforme a necessidade</span><span>Escopo aprovado antes de qualquer excedente</span></div></div></section>
 <section className="planSection shell"><p className="eyebrow">TRANSPARÊNCIA</p><h2>Algumas atividades precisam de especialistas específicos.</h2><p>Advocacia, representação jurídica, contabilidade, folha não contratada, medicina ocupacional, segurança do trabalho, hunting especializado, grandes projetos e licenças podem ser realizados por parceiros ou profissionais habilitados.</p><p><b>Quando isso acontecer, avisaremos antes. Sem surpresa no meio do caminho.</b></p><p className="upgrade"><b>Quando rever o plano:</b> {plan.upgrade}</p></section>
 <section className="planSection faq shell">{['Quem atende minha empresa?','Como funciona o suporte?','O que é vaga padrão?','Posso contratar vagas adicionais?','A Benê substitui a contabilidade?','A Benê presta assessoria jurídica?','Existe contrato mínimo?','Os planos podem ser personalizados?','Como a Benê acompanha a evolução?'].map((q,i)=><details key={q}><summary>{q}</summary><p>{i===0?'Amanda coordena a estratégia, o relacionamento e uma rede de especialistas e parceiros independentes acionados conforme a necessidade.':i===1?'O canal, a cadência de reuniões e os responsáveis são definidos no onboarding conforme o plano.':i===2?'Posições operacionais, administrativas ou comerciais dentro da complexidade e do volume do plano.':i===3?'Sim, após avaliação de capacidade, escopo e orçamento aprovado.':i===4?'Não. A Benê coordena a interface de gestão de pessoas; folha e obrigações continuam com profissionais habilitados.':i===5?'Não. Temas jurídicos são encaminhados à assessoria habilitada do cliente ou a profissional contratado separadamente.':i===6?'Sim. A vigência mínima é de três meses; depois, aplica-se aviso de 30 dias.':i===7?'Ajustes podem ser avaliados e são formalizados antes da execução.':'Por meio de prioridades, reuniões, indicadores compatíveis com o plano e próximos passos registrados.'}</p></details>)}</section>
 <section className="cta" id="contato"><div className="shell"><h2>Você não precisa resolver o RH sozinho.</h2><p>Conte como sua empresa funciona hoje. Vamos confirmar juntos qual estrutura faz sentido antes da contratação.</p><div className="centerActions"><a className="button" href={contact} target="_blank" rel="noopener noreferrer">Conversar pelo WhatsApp</a><Link className="button lightButton" href="/agendar">Agendar uma conversa</Link><Link className="ctaTextLink" href="/#diagnostico">Fazer o diagnóstico gratuito</Link></div><p className="micro">Sem empurrar um pacote maior do que você precisa.</p></div></section>
 </main><SiteFooter/></>
}

