export type Plan={slug:string;name:string;price:string;subtitle:string;intro:string;badge?:string;highlights:string[];fit:string[];sections:{title:string;items:string[]}[];receives:string[];cta:string;upgrade:string};
export const commonStart=[
'Diagnóstico inicial da operação de pessoas','Levantamento de cargos, funções e responsabilidades','Identificação de gargalos e riscos operacionais','Organização das informações dos colaboradores','Processos essenciais, checklists e prioridades','Onboarding e desligamento organizados','Suporte ao gestor em dúvidas, feedbacks e conflitos simples'
];
export const plans:Record<string,Plan>={
start:{slug:'start',name:'Benê Start',price:'R$ 1.500/mês',subtitle:'Seu RH organizado desde o começo.',intro:'Para pequenas empresas com até 10 pessoas que precisam organizar o RH, contratar melhor e cuidar das rotinas de pessoas sem criar um departamento interno.',highlights:['Até 10 pessoas','1 vaga padrão ativa','Onboarding','Rotinas essenciais de RH','Suporte mensal'],fit:['O RH ficou improvisado com o crescimento','Admissões e desligamentos dependem da memória de alguém','Documentos e informações estão espalhados','Você precisa contratar, mas não possui recrutador','O RH acaba ficando nas mãos do dono','A contabilidade executa o DP, mas ninguém gerencia pessoas'],sections:[
{title:'Diagnóstico e implantação',items:commonStart.slice(0,5)},
{title:'Recrutamento e seleção',items:['1 vaga padrão ativa por vez','Briefing, descrição e revisão do perfil','Divulgação nos canais adequados','Triagem, pré-seleção e entrevista inicial de RH','Parecer e encaminhamento dos melhores perfis','Apoio na decisão, comunicação e integração']},
{title:'Rotinas de RH',items:['Processo de admissão e checklist de integração','Onboarding e desligamento','Organização documental e de movimentações','Formulários e modelos internos','Interface organizada entre RH, contabilidade e Departamento Pessoal']},
{title:'Suporte ao gestor',items:['Canal de suporte para dúvidas de RH','Preparação de feedbacks e conversas difíceis','Modelos de comunicação','Orientação sobre conflitos simples e decisões de pessoas']}
],receives:['Processos organizados','Checklists, documentos e modelos','Acompanhamento mensal','Indicadores básicos e pontos de atenção','Orientação especializada','Plano de prioridades e histórico das ações'],cta:'Quero organizar meu RH',upgrade:'Quando a equipe ultrapassa 10 pessoas, há mais de uma vaga ativa ou a empresa precisa de gestão, treinamento e cultura.'},
pro:{slug:'pro',name:'Benê Pro',price:'R$ 3.500/mês',subtitle:'RH estruturado para empresas que estão crescendo.',intro:'Para empresas com até 30 pessoas que precisam ir além da organização básica e começar a gerir pessoas, desenvolver lideranças, acompanhar resultados e fortalecer a cultura.',badge:'MAIS INDICADO',highlights:['Até 30 pessoas','2 vagas padrão ativas','Tudo do Start','Gestão de pessoas','Treinamento','Cultura e indicadores'],fit:['O dono ainda centraliza problemas de pessoas','Os gestores precisam aprender a gerir','Existe dificuldade de retenção','O crescimento cria ruído entre áreas','Feedbacks não possuem padrão','Ninguém acompanha indicadores de pessoas'],sections:[
{title:'Inclui o Benê Start',items:commonStart},
{title:'Gestão de pessoas',items:['Estruturação ou revisão de cargos e responsabilidades','Competências, feedbacks e reuniões 1:1','Acompanhamento do período de experiência','Avaliação de desempenho e planos de melhoria','Orientação aos gestores']},
{title:'Recrutamento',items:['Até 2 vagas padrão ativas simultaneamente','Entrevistas por competência e pareceres','Organização e acompanhamento do funil','Apoio ao gestor, integração e acompanhamento inicial']},
{title:'Treinamento e desenvolvimento',items:['Levantamento de necessidades','Plano de desenvolvimento e treinamentos essenciais','Treinamento de gestores e materiais de apoio','Acompanhamento das ações']},
{title:'Cultura, clima e indicadores',items:['Diagnóstico de cultura e valores traduzidos em comportamentos','Comunicação interna e ações de engajamento','Pesquisas rápidas de clima e plano de ação','Headcount, admissões, desligamentos, turnover, recrutamento e treinamentos']}
],receives:['Acompanhamento da operação','Reunião gerencial','Visão dos indicadores','Ações realizadas e pendências','Prioridades e próximos passos','Recomendações e acompanhamento dos planos de ação'],cta:'Quero estruturar meu RH',upgrade:'Quando a empresa ultrapassa 30 pessoas, precisa de até 3 vagas simultâneas ou demanda planejamento, performance e educação corporativa estruturados.'},
full:{slug:'full',name:'Benê Full',price:'R$ 7.000/mês',subtitle:'Uma estrutura completa de RH sem montar um departamento inteiro dentro de casa.',intro:'Para empresas com até 60 pessoas que precisam conectar RH, liderança, desempenho, educação corporativa, indicadores e estratégia.',highlights:['Até 60 pessoas','3 vagas padrão ativas','Tudo do Pro','RH estratégico','Performance','Educação corporativa','Inteligência de pessoas'],fit:['A empresa cresceu rapidamente','Decisões de pessoas impactam diretamente o negócio','Existe mais de uma liderança','Há necessidade frequente de contratação','Performance e cultura não são acompanhadas','Falta visão executiva dos indicadores de pessoas'],sections:[
{title:'Inclui o Benê Pro',items:['Tudo do Start','Gestão de pessoas','Treinamento e desenvolvimento','Cultura, clima e indicadores']},
{title:'Recrutamento ampliado',items:['Até 3 vagas padrão simultâneas','Gestão completa do funil e indicadores','Planejamento de contratações e necessidade de pessoas','Acompanhamento dos candidatos e apoio aos gestores']},
{title:'RH estratégico e performance',items:['Planejamento de pessoas e headcount','Estrutura organizacional, papéis e responsabilidades','Desenvolvimento de liderança','Avaliação de desempenho, competências, PDI e ciclos de feedback','Plano de ação trimestral']},
{title:'Educação corporativa',items:['Diagnóstico das necessidades','Calendário e trilhas de aprendizagem','Treinamentos, conteúdos e materiais para gestores','Acompanhamento da participação e das necessidades futuras']},
{title:'Compliance de pessoas',items:['Apoio preventivo em conjunto com a contabilidade e a assessoria jurídica do cliente','Checklists, organização documental e políticas internas','Código de conduta e fluxos de ocorrências quando necessários','Direcionamento ao jurídico ou à contabilidade']},
{title:'Inteligência e acompanhamento executivo',items:['Headcount, turnover, absenteísmo, admissões e desligamentos','Recrutamento, performance, desenvolvimento, treinamentos e clima','Reunião com a liderança, recomendações e prioridades','Evolução dos planos de ação']}
],receives:['Visão executiva de pessoas','Dashboard e indicadores','Reuniões periódicas com a liderança','Plano de ação trimestral','Acompanhamento de performance, cultura e desenvolvimento','Coordenação de especialistas e parceiros'],cta:'Quero um RH mais estratégico',upgrade:'Acima de 60 pessoas, com maior volume ou complexidade, a Benê avalia uma proposta personalizada.'}
};
