import {notFound} from 'next/navigation';
import type {Metadata} from 'next';
import Link from 'next/link';
import {SiteHeader} from '../../../components/SiteHeader';
import {SiteFooter} from '../../../components/SiteFooter';
import {articlesEn,getArticleEn} from '../blog-data-en';
export function generateStaticParams(){return articlesEn.map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const article=getArticleEn(slug);if(!article)return{};return{title:article.title,description:article.description,alternates:{canonical:`/en/blog/${slug}`}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const article=getArticleEn(slug);if(!article)return notFound();return <><SiteHeader/><main id="conteudo" className="articlePage"><header className="articleHero"><div className="articleShell"><p className="breadcrumbs"><Link href="/en">Home</Link> / <Link href="/en/blog">Blog</Link> / {article.category}</p><span className="articleCategory">{article.category}</span><h1>{article.title}</h1><p>{article.description}</p><div className="articleMeta"><span>By Amanda Stamboni</span><span>{article.reading}</span><span>Updated August 28, 2026</span></div></div></header><article className="articleBody articleShell"><p className="articleIntro">{article.intro}</p>{article.sections.map(section=><section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}{section.items&&<ul>{section.items.map(item=><li key={item}>{item}</li>)}</ul>}</section>)}<div className="articleClosing"><h2>Your next step</h2><p>{article.closing}</p><div className="heroActions"><Link className="button" href="/en/schedule">Talk to Benê</Link><Link className="buttonSecondary" href="/en#diagnostico">Start the diagnosis</Link></div></div><nav className="articleNav" aria-label="Blog navigation"><Link href="/en/blog">← Back to blog</Link><Link href="/en/schedule">Schedule a conversation →</Link></nav></article></main><SiteFooter/></>}
